### ISSUE TITLE
--export-obj available in command line 

### ISSUE THREAD

**Issue by xyzdevops** [slic3r/Slic3r#4900]
In the manual it says about this feature but in practice it doesn't work.

The help message returned by '--help' only lists '--output-svg'.

I am very confused why the manual thinks this is an already existing feature.

It seems to exist in the slic3r.cpp, but the flag is never able to be read.

Version 1.3

**Comment by lordofhyphens** [comment]
There are 2 CLI clients currently. One is c++ based, the other is perl

**Comment by xyzdevops** [comment]
The readme should mention the perl one.

The manual should also be sectioned to clearly show the features of each CLI, currently it is highly confusing.

**Comment by lordofhyphens** [comment]
slic3r/Slic3rManual awaits your pull requests.

**Comment by xyzdevops** [comment]
I can't improve the document until I figure out how it works. Spent all day trying to dockerise the app so I can run the perl CLI to see if it will take this --export-obj flag.

My ultimate aim is to use the --cut-grid and the --export-obj so my derivative files are in a useful format.

**Comment by lordofhyphens** [comment]
Why would you need to dockerize the application? The downloads from dl.slic3r.org/dev are all self contained and use the Perl interface (as the c++cli is experimental until support gets ported).

Even then, building the Perl side leverages local::lib as to not break your local system.

**Comment by xyzdevops** [comment]
Because I want to run it in kubernetes.

Also I have Mac os Catalina so it wouldn't just run.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by lordofhyphens** [comment]
For Catalina:

https://dl.slic3r.org/dev/mac/jenkins

No idea why the Travis builds don't work and the older Jenkins do on Mojave
and newer.

Have been trying on and off for months to figure that out.

**Comment by xyzdevops** [comment]
Can someone please tell me if the --export-obj is a feature or not, as it doesn't seem to work on either CLI.

**Comment by lordofhyphens** [comment]
I just checked with the C++ CLI.
````
./slic3r --export-obj <inputfilename>
````
should produce <inputfilename>.obj

You can check the CLI options in the code via `xs/src/libslic3r/PrintConfig.cpp` and via `slic3r --help`.

I just ran across a bug where apparently `stl_generate_shared_vertices()` in admesh gets caught in an infinite loop. I am currently looking into it.

**Comment by lordofhyphens** [comment]
Unfortunately, apparently none of that has changed in years and so I am tracking down what could have broken.

**Comment by lordofhyphens** [comment]
Ok, looks like the method expect the mesh to be repaired. I've committed an update which calls `repair()` on the mesh copy used for export.

**Comment by lordofhyphens** [comment]
@xyzdevops update master branch and give it a try.

**Comment by lordofhyphens** [comment]
@Oekn5w can you do a diff check around your code with the call to repair() removed in `IO.cpp:158`

to see if you can see if  the matrix reload changes broke anything?

**Comment by xyzdevops** [comment]
I still get:
 Unknown option: export-obj

In the --help there is no such options for export as listed in the manual.

**Comment by lordofhyphens** [comment]
On the c++ cli? On a checkout from master?

**Comment by lordofhyphens** [comment]
Please do a fresh checkout of the master branch, build it with CMake.

**Comment by xyzdevops** [comment]
`
FROM ubuntu:latest

RUN apt-get update
COPY sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y git

WORKDIR /app
RUN git clone https://github.com/Slic3r/Slic3r.git .

ENV LDLOADLIBS=-lstdc++
RUN apt-get install -y build-essential cpanminus liblocal-lib-perl cmake
RUN apt-get build-dep -y slic3r
RUN apt-get install -y libxmu-dev freeglut3-dev
RUN apt-get install -y libboost-thread-dev libboost-system-dev libboost-filesystem-dev
RUN apt-get install -y libextutils-parsexs-perl
RUN apt-get install -y libcurl4-openssl-dev

RUN mkdir build && cd build && cmake ../src && cmake --build . -- -j4

`

That Dockerfile should grab your latest changes.

I'm just testing the perl vs c++ without --export-object, then with it subsequently.

I will let you know what happens.

**Comment by xyzdevops** [comment]
the c++ --cut-grid no longer works at all for my model, so it is a regression from my perspective.

the c++ '--export-obj --cut-grid...' does nothing, which is better than rejecting the command like the perl CLI does.

**Comment by Oekn5w** [comment]
I'll look into the mesh flattening in the model's function again, didn't find anything briefly.

But I'm not quite following the conversation here, is this about differences between perl and c++ CLI, or the export not working?

If the latter and the repair fixes that, then I'd like to know how to reproduce (although, to be fair, I didn't actually try anything, today at least)

**Comment by xyzdevops** [comment]
The comparison between languages is to sanity check what the state of some features are; to isolate bugs
________________________________

**Comment by lordofhyphens** [comment]
Export obj is NOT in the Perl side. I don't intend to port it.

**Comment by lordofhyphens** [comment]
@Oekn5w I just tried to export obj with a 20mm stl box from the c++ cli.

Infinite loop inside shared vertex generation.
